### PR TITLE
feat(demo): create new page layout for plasma components

### PR DESCRIPTION
**Pull request by GermainBergeron**
### Proposed Changes

Create the new page for the plasma components
Move the guidelines in a separate component

### Potential Breaking Changes

None

### Acceptance Criteria

-   [ ] The proposed changes are covered by unit tests
-   [ ] The potential breaking changes are clearly identified
-   [ ] [README.md](https://github.com/coveo/react-vapor/blob/master/README.md) is adjusted to reflect the proposed changes (if relevant)

### CODE REVIEW

**Comment by GermainBergeron** [comment]
Here's the link to my custom page https://vapor.coveo.com/feature/PR-2360/index.html#/input/ButtonV2

**Comment by aiheon** [comment]
> Here's the link to my custom page https://vapor.coveo.com/feature/PR-2360/index.html#/input/ButtonV2

It's so nice to see all of it put together!!! :grin:

**Review by aiheon — APPROVED** [review]

**Review by gdostie — APPROVED** [review]
The guidelines tab have lost some padding
image

**Comment by GermainBergeron** [comment]
For the guidelines I didn't want to break the other layout (the one using the old style). I'll make a different PR to handle that

**Pull request merged**
