### PR TITLE
Nextnext

### PR DESCRIPTION
**Pull request by aiheon**
### Proposed Changes

This is the merged between master and next, so it should be the most up-to-date version of React-Vapor.
By merging into next, we will get a new version of the package than we can then use to bump the admin for the spike here: https://coveord.atlassian.net/browse/ADUI-6611

### Potential Breaking Changes

Yes :bear: 

### Acceptance Criteria

-   [ ] The proposed changes are covered by unit tests
-   [ ] The potential breaking changes are clearly identified
-   [ ] [README.md](https://github.com/coveo/react-vapor/blob/master/README.md) is adjusted to reflect the proposed changes (if relevant)

### CODE REVIEW

**Comment by gdostie** [comment]
Shouldn't we fix the breaking changes inside admin-ui before doing this?

**Comment by gdostie** [comment]
Also, the next branch seems to be 69 commits behind master, I think it should be rebased on the tip of master before attempting to merge it.
image

**Comment by aiheon** [comment]
> Shouldn't we fix the breaking changes inside admin-ui before doing this?

We can't because there's missing component used in admin-ui that are not in Next. The admin just explode :sweat_smile:

**Comment by aiheon** [comment]
> Also, the next branch seems to be 69 commits behind master, I think it should be rebased on the tip of master before attempting to merge it.
> image

Yes, nextnext is the rebase!

**Pull request closed without merging**
