### PR TITLE
UITOOL-421/rename reactvaporstate

### PR DESCRIPTION
**Pull request by aiheon**
### Proposed Changes

https://coveord.atlassian.net/browse/UITOOL-421

For consistency we are renaming ReactVaporState/Reducers/Mocks etc to Plasma.

### Potential Breaking Changes

**BREAKING CHANGE: IReactVaporState as been renamed PlasmaState**

### Acceptance Criteria

-   [ ] The proposed changes are covered by unit tests
-   [ ] The potential breaking changes are clearly identified
-   [ ] [README.md](https://github.com/coveo/plasma/blob/master/README.md) is adjusted to reflect the proposed changes (if relevant)

### CODE REVIEW

**Comment by GermainBergeron** [comment]
I'm pretty certain this is a breaking change, I don't see any footer in your commit pointing to a breaking change

**Review by toofff — APPROVED** [review]
it seems all good to me, however you're going to have a BC Break

**Comment by aiheon** [comment]
> I'm pretty certain this is a breaking change, I don't see any footer in your commit pointing to a breaking change

it is? :eyes:  

Oops, I'll fix that commit then :sweat_smile:

**Review by GermainBergeron — APPROVED** [review]
Code looks good, but make sure it bump a major version!

**Review by gdostie — APPROVED** [review]

**Comment by aiheon** [comment]
image

J'ai encore un peu foutu le bordel dans mes commits, mais ça devrait être bon :see_no_evil:

**Pull request merged**
