### PR TITLE
fix(multiselect): fix the custom value selected option box from demo

### PR DESCRIPTION
**Pull request by sallainCoveo**
After the selection of a custom value, using a multi select filter, the selected option box now
appears in the selected option area.

### Proposed Changes

Initially, only the default items, present in the dropdown menu selection, are considered on the creation of the selected option box. However, the previous method was necessary as it would take consideration of the display value, and not only the selected value.  Nevertheless, because the custom values are not included in the items props, I suggested that the method would fetch the remaining selected option (from the selected props) and included in the returned array of IItemBoxProps. In doing so, the custom values may be included in the selection option area.

### Acceptance Criteria

-   [ ] The proposed changes are covered by unit tests
-   [ ] The potential breaking changes are clearly identified
-   [ ] [README.md](https://github.com/coveo/react-vapor/blob/master/README.md) is adjusted to reflect the proposed changes (if relevant)

### CODE REVIEW

**Comment by FelixBlaisThon** [comment]
Nice! a question remains for me. With these changes, is it still necessary to keep the + button on the right? it doesn't seem to add the value to the selected ones @oliviertaillon

**Comment by oliviertaillon** [comment]
@FelixBlaisThon Good point, I couldn't find what it is doing. @sallainCoveo what is supposed to happen when clicking on the ( + ) icon ? 
(Maybe out of scope for this PR)

**Comment by FelixBlaisThon** [comment]
It triggers the same action 'ADD_VALUE_STRING_LIST' as the one when you click on the custom item on the dropdown, but it doesn't add it :/

**Comment by sallainCoveo** [comment]
@oliviertaillon ,

Honestly, I'm not sure. It was already present when I was working on this bug. I suppose that the initial purpose of this icon would be to add a custom item (an alternative action of clicking on the
option on the drop down menu). I noticed that this button didn't work, but it would seems that this
issue is out of the scope of the initial bug. Do you think it would be interesting to have both options for the end-user experience?

**Comment by oliviertaillon** [comment]
> Do you think it would be interesting to have both options for the end-user experience?

I don't think the + icon add much value, we could remove it in a different PR. The part that is more confusing is that you have to first enter a filter, then you are able to add this as a custom value. But this is a different story not relevant to this current PR.

**Comment by rosalie-liu** [comment]
hmm it seems there is a little problem with the format?

**Comment by sallainCoveo** [comment]
@rosalie-liu,

Thanks for the observation! I did use the command npm run lintfix to format my file, but I might have created a few issues along the way. I'll try to add the Prettier plugin to correct these strangely formatted files.

**Pull request closed without merging**
