### PR TITLE
front autofocus props

### PR DESCRIPTION
**Pull request by rousselm4**
Need for a bugfix.

### CODE REVIEW

**Comment by GermainBergeron** [comment]
```
ERROR in /home/travis/build/coveo/react-vapor/src/components/input/Input.tsx
./src/components/input/Input.tsx
[tsl] ERROR in /home/travis/build/coveo/react-vapor/src/components/input/Input.tsx(168,21)
      TS2339: Property 'autofocus' does not exist on type 'DetailedHTMLProps<InputHTMLAttributes<HTMLInputElement>, HTMLInputElement>'.
```

**Comment by MichelML** [comment]
`      TS2339: Property 'autofocus' does not exist on type 'DetailedHTMLProps<InputHTMLAttributes<HTMLInputElement>, HTMLInputElement>'.
` in your build 🤕

**Comment by rousselm4** [comment]
@MichelML @GermainBergeron it should be fixed now (waiting for the build). I added a test too.

**Comment by rousselm4** [comment]
C'est fixed pour vrai la!

**Pull request merged**
